enum UnitPriceCategory {
  shutCrete,
  excavation,
  breaker,
  foundationStabilizationGravel,
  c16Concrete,
  reinforcedConcreteWorkmanshipWithPlywood,
  c30Concrete,
  c35Concrete,
  c40Concrete,
  s420Steel,
  eps14Dns,
  proofBitumenMembrane,
  bitumenSliding,
  cementSliding,
  drainPlate,
  aeratedConcreteYtong,
  aeratedConcreteLabor,
  steelConstructionBraasRoof,
  steelScaffolding,
  windowJoineryRehau,
  wroughtIronRailing,
  aluminumRailing,
  sinterFlex4Facade,
  precast3FacadePlaster1Facade,
  plaster,
  painting,
  cementBasedFlexInsulation,
  drywall,
  covingPlaster,
  screed300Doses,
  marbleFloorBilecik,
  marbleStepBilecik,
  marbleWindowsillBilecik,
  ceramicTileVitraVersus,
  laminatedSerifoglu,
  steelDoorKale,
  entranceDoor,
  ironFireDoor,
  lacqueredDoorArtella,
  shinyLacqueredKitchenCupboardAster,
  matteLacqueredKitchenCupboardAster,
  quartzCountertopCimstone,
  lacqueredCabinet,
  lacqueredFloorPlinth,
  mechanicalInfrastructure,
  airConditionerArcelik,
  vrfMultiSplitMitsubishiElectric,
  ventilation,
  galvanize25TonWaterTankEsinoks,
  elevation10PersonKone,
  elevation6PersonKone,
  sinkVitra,
  sinkBatteryVitra,
  concealedCisternVitra,
  showerHuppe100x100,
  showerBatteryVitra,
  kitchenFaucetAndSinkFranke,
  electricalInfrastructure,
  generatorAksa160,
  paddleBoxBuiltInOvenCookTopDishwasherFranke,
  averageGarden,
  interlockingPavingStone,
  carLift,
  automaticBarrier,
  automaticShutter,
  trapezoidalSheetCurtain,
  mobilizationDemobilization,
  crane55Ton,
  siteSafety,
  siteExpenses,
  sergeantGrossWage,
  siteChiefGrossWage,
  projectsFeesPayments;
}

extension UnitPriceCategoryExtension on UnitPriceCategory {
  String get nameTr {
    return switch (this) {
    UnitPriceCategory.shutCrete => "Shutcrete",
    UnitPriceCategory.excavation => "Hafriyat",
    UnitPriceCategory.breaker => "Kırıcı",
    UnitPriceCategory.foundationStabilizationGravel => "Mıcır",
    UnitPriceCategory.c16Concrete => "C16 Beton",
    UnitPriceCategory.reinforcedConcreteWorkmanshipWithPlywood => "Plywood",
    UnitPriceCategory.c30Concrete => "C30 Beton",
    UnitPriceCategory.c35Concrete => "C35 Beton",
    UnitPriceCategory.c40Concrete => "C40 Beton",
    UnitPriceCategory.s420Steel => "S420 İnşaat Demiri",
    UnitPriceCategory.eps14Dns => "14 Dansite Eps",
    UnitPriceCategory.proofBitumenMembrane => "Bitüm Esaslı Proof Membran",
    UnitPriceCategory.bitumenSliding => "Bitüm Esaslı Sürme İzolasyon",
    UnitPriceCategory.cementSliding => "Çimento Esaslı Kristalize Sürme İzolasyon",
    UnitPriceCategory.drainPlate => "Drenaj Levhası",
    UnitPriceCategory.aeratedConcreteYtong => "Ytong",
    UnitPriceCategory.aeratedConcreteLabor => "Gazbeton İşçilik",
    UnitPriceCategory.steelConstructionBraasRoof => "Çelik konstrüksiyon Braas Çatı",
    UnitPriceCategory.steelScaffolding => "Korkuluklu çelik iskele",
    UnitPriceCategory.windowJoineryRehau => "Rehau sürgülü, monoblok panjurlu",
    UnitPriceCategory.wroughtIronRailing => "Ferforje Korkuluk",
    UnitPriceCategory.aluminumRailing => "Alüminyum Korkuluk",
    UnitPriceCategory.sinterFlex4Facade => "4 cephe Sinterflex",
    UnitPriceCategory.precast3FacadePlaster1Facade => "3 cephe Prekast - 1 cephe Sıva, Boya",
    UnitPriceCategory.plaster => "Alçı sıva",
    UnitPriceCategory.painting => "Dyo boya",
    UnitPriceCategory.cementBasedFlexInsulation => "Çimento Esaslı Tam Elastik Sürme İzolasyon",
    UnitPriceCategory.drywall => "Alçıpan",
    UnitPriceCategory.covingPlaster => "Kartonpiyer",
    UnitPriceCategory.screed300Doses => "300 Doz Şap",
    UnitPriceCategory.marbleFloorBilecik => "Bilecik Beji Mermer",
    UnitPriceCategory.marbleStepBilecik => "Bilejik Beji Basamak",
    UnitPriceCategory.marbleWindowsillBilecik => "Bilejik Beji Denizlik",
    UnitPriceCategory.ceramicTileVitraVersus => "Vitra Versus Seramik",
    UnitPriceCategory.laminatedSerifoglu => "Şerifoğlu Lamine Parke",
    UnitPriceCategory.steelDoorKale => "Kale Çelik Kapı",
    UnitPriceCategory.entranceDoor => "Apartman Giriş Kapısı",
    UnitPriceCategory.ironFireDoor => "Yangın kapısı",
    UnitPriceCategory.lacqueredDoorArtella => "Artella Lake Ahşap Kapı",
    UnitPriceCategory.shinyLacqueredKitchenCupboardAster =>  "Aster Parlak Lake",
    UnitPriceCategory.matteLacqueredKitchenCupboardAster => "Aster Mat Lake",
    UnitPriceCategory.quartzCountertopCimstone => "Çimstone Mutfak Tezgahı",
    UnitPriceCategory.lacqueredCabinet => "Lake Dolap",
    UnitPriceCategory.lacqueredFloorPlinth =>  "Lake Süpürgelik",
    UnitPriceCategory.mechanicalInfrastructure => "Mekanik Tesisat Altyapı İşleri",
    UnitPriceCategory.airConditionerArcelik => "Arçelik Klima",
    UnitPriceCategory.vrfMultiSplitMitsubishiElectric =>  "Mitshubishi Electric Multi Split",
    UnitPriceCategory.ventilation => "Havalandırma",
    UnitPriceCategory.galvanize25TonWaterTankEsinoks => "Esinoks 25 Ton Galvaniz",
    UnitPriceCategory.elevation10PersonKone => "Kone 10 Kişilik Asansör",
    UnitPriceCategory.elevation6PersonKone => "Kone 6 Kişilik Asansör",
    UnitPriceCategory.sinkVitra => "Vitra Lavabo",
    UnitPriceCategory.sinkBatteryVitra => "Vitra Lavabo Bataryası",
    UnitPriceCategory.concealedCisternVitra => "Vitra Gömme Rezervuar ve Taşı",
    UnitPriceCategory.showerHuppe100x100 => "Hüppe Duşakabin 100x100",
    UnitPriceCategory.showerBatteryVitra => "Vitra Duş Bataryası",
    UnitPriceCategory.kitchenFaucetAndSinkFranke => "Franke Evye ve Batarya",
    UnitPriceCategory.electricalInfrastructure => "Elektrik Tesisat Altyapı İşleri",
    UnitPriceCategory.generatorAksa160 => "Aksa 160 Kva Jeneratör",
    UnitPriceCategory.paddleBoxBuiltInOvenCookTopDishwasherFranke => "Franke Ankastre Beyaz Eşya (Davlumbaz, Fırın, Set Üstü Ocak, Bulaşık Makinesi)",
    UnitPriceCategory.averageGarden => "Bahçe, Çim, Ağaç vs.",
    UnitPriceCategory.interlockingPavingStone => "Kilit Taşı",
    UnitPriceCategory.carLift => "Araç Asansörü",
    UnitPriceCategory.automaticBarrier => "Açık Otopark Otomatik Bariyer",
    UnitPriceCategory.automaticShutter => "Otomatik Kepenk",
    UnitPriceCategory.trapezoidalSheetCurtain => "Trapez sac çevre perdesi",
    UnitPriceCategory.mobilizationDemobilization => "Mobilizasyon - Demobilizasyon",
    UnitPriceCategory.crane55Ton => "55 Ton Vinç",
    UnitPriceCategory.siteSafety => "Şantiye güvenlik önlemleri",
    UnitPriceCategory.siteExpenses => "Şantiye, Ofis, Elektrik, Su vb.",
    UnitPriceCategory.sergeantGrossWage => "Şantiye Çavuşu Brüt Maaş",
    UnitPriceCategory.siteChiefGrossWage => "Şantiye Şefi Brüt Maaş",
    UnitPriceCategory.projectsFeesPayments => "Projeler, resmi harçlar, ödemeler",
    };
  }
}